Docker: add dockerfile and README.md
inclavare-containers/docker-attestation-agent pull request #1
Opened 2024-03-13 07:53 UTC by 1570005763

1. Introduce CoCo/guest-components as a submodule.
2. Offer two types of AA images for gRPC and ttrpc interface.
3. Provide a guide for image building and running in readme file.

2024-03-13 08:00 UTC, Xynnn007 reviewed
good. 另外可以看一下如何在github action里增加镜像发布功能，这样能把AA的镜像直接通过github action流水线构建发布到package里

参考https://github.com/confidential-containers/trustee/blob/main/.github/workflows/kbs-build-and-push.yaml

2024-03-13 08:00 UTC, Xynnn007 commented on Dockerfile.ttrpc
> +CMD [ "attestation-agent" ]
在这块加一个VOLUME，并指定这个sock文件，搜一下dockerfile文档里的VOLUME写法

2024-03-13 08:13 UTC, 1570005763 commented on Dockerfile.ttrpc
> +CMD [ "attestation-agent" ]
Great suggestions. And I should be opening other PRs to implement CI/CD and image release functionalities.

2024-03-26 08:18 UTC, Xynnn007 commented on Dockerfile.ttrpc
> +RUN apt-get update && apt-get install -y protobuf-compiler
我们需要这个吗？

2024-03-26 08:18 UTC, Xynnn007 commented on Dockerfile.ttrpc
> +    apt-get update && apt-get install -y libtdx-attest-dev libsgx-dcap-quote-verify
我建议把这两大坨合成一个RUN语句，然后最后一并执行rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

2024-04-01 02:45 UTC, jiazhang0 requested changes

2024-04-01 02:45 UTC, jiazhang0 commented on README.md
> +Attestation Agent (AA) is a service function set for attestation procedure in Confidential Containers. It provides several kinds of service APIs related to attestation.
改成：`(aka AA)`

2024-04-01 02:45 UTC, jiazhang0 commented on README.md
> +Attestation Agent (AA) is a service function set for attestation procedure in Confidential Containers. It provides several kinds of service APIs related to attestation.
s/service function set/service/

2024-04-01 02:45 UTC, jiazhang0 commented on README.md
> +Attestation Agent (AA) is a service function set for attestation procedure in Confidential Containers. It provides several kinds of service APIs related to attestation.
s/for attestation/for the attestation/

2024-04-01 02:45 UTC, jiazhang0 commented on README.md
> +Attestation Agent (AA) is a service function set for attestation procedure in Confidential Containers. It provides several kinds of service APIs related to attestation.
s/Confidential Containers/Confidential Computing/

2024-04-01 02:45 UTC, jiazhang0 commented on README.md
> +This repository packages the Attestation Agent (AA) into an easy-to-use image.
s/Attestation Agent (AA)/AA/

2024-04-01 02:55 UTC, jiazhang0 requested changes

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +This repository packages AA into an easy-to-use image.
Move `For more details, please visit [Attestation Agent](https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/README.md)` behind `This repository packages AA into an easy-to-use image.`

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +# Build Attestation Agent (AA) Image
不用每次都这样写了。你最前面写清楚AA是缩写，后面都用缩写AA就行了。

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +AA offers 2 kinds of interface, gRPC and ttrpc. Please choose corresponding dockerfile to build your AA image.
s/dockerfile/Dockerfile/

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +- A Docker-enabled system
s/Docker-enabled system/Ensure Docker installed on your system/

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +```
在```后面添加`shell`

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +git clone --recurse-submodules git@github.com:1570005763/attestation-agent-image.git && cd attestation-agent-image
这行超过80个字符了，改成：
```
git clone --recurse-submodules \
    git@github.com:1570005763/attestation-agent-image.git && \
    cd attestation-agent-image
```

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +- A Docker-enabled system
改下

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +- Already have AA image
这啥表述啊？改成Installed AA image

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +    - Intel SGX DCAP
去掉DCAP

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +## Config
Configuration

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +- Usage： specify the KBC type and KBS address.
冒号后面多了个空格

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +- Usage： determine log level.
ditto

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +Or run image in interactive mode.
这段就没啥用，属于教不懂docker的人的步骤？需要在这里教吗？删除

2024-04-01 02:55 UTC, jiazhang0 commented on README.md
> +Or run image in interactive mode.
ditto

2024-04-01 02:56 UTC, jiazhang0 requested changes

2024-04-01 02:56 UTC, jiazhang0 commented on Dockerfile.grpc
> +RUN curl -L https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | tee intel-sgx-deb.key | apt-key add - && \
这种超过80行的都改成\换行加4空格缩进，否则可读性太差

2024-04-01 07:08 UTC, 1570005763 commented on Dockerfile.ttrpc
> +CMD [ "attestation-agent" ]
VOLUME added.

2024-04-01 07:23 UTC, 1570005763 commented on Dockerfile.ttrpc
> +RUN apt-get update && apt-get install -y protobuf-compiler
Removed.

2024-04-01 07:23 UTC, 1570005763 commented on Dockerfile.ttrpc
> +    apt-get update && apt-get install -y libtdx-attest-dev libsgx-dcap-quote-verify
Verified.

2024-04-01 07:25 UTC, 1570005763 commented on Dockerfile.grpc
> +RUN curl -L https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | tee intel-sgx-deb.key | apt-key add - && \
这里我增加了换行。不过这里超链接比较长，可能没法严格限制在80字符以内。

2024-04-02 08:02 UTC, jiazhang0 approved these changes

2024-04-05 04:12 UTC, merged